version: '3'

services:
  stt:
    build:
      context: stt/.
    container_name: stt
    expose:
      - "8000"
    depends_on:
      - mongo
    env_file:
      - "./.env"
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_COLLECTION=${MONGO_COLLECTION}
    volumes:
      - ./stt:/api
    networks:
      - deepspeech
  tts:
    build:
      context: tts/.
    container_name: tts
    expose:
      - "8000"
    depends_on:
      - mongo
    env_file:
      - "./.env"
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_COLLECTION=${MONGO_COLLECTION}
    volumes:
      - ./tts:/api
    networks:
      - deepspeech
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - deepspeech  
    depends_on:
      - stt
      - tts
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www/:/var/www/certbot/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    env_file:
      - "./.env"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    networks:
      - deepspeech

networks:
  deepspeech:
