version: '3'

services:
  stt:
    build:
      context: stt/.
    container_name: stt
    expose:
      - "8000"
    volumes:
      - ./stt:/api
      - ./utils:/api/utils
    depends_on:
      - mongo
    env_file:
      - "./.env"
    networks:
      - deepspeech
  tts:
    build:
      context: tts/.
    container_name: tts
    expose:
      - "8000"
    volumes:
      - ./tts:/api
      - ./utils:/api/utils
    depends_on:
      - mongo
    env_file:
      - "./.env"
    networks:
      - deepspeech
  nginx:
    image: nginx:latest
    # build:
    #   context: nginx/.
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docs/redoc-static.html:/usr/share/nginx/html/redoc-static.html
    env_file:
      - "./.env"
    networks:
      - deepspeech  
    depends_on:
      - stt
      - tts
  mongo:
    image: mongo:latest
    container_name: mongo_db_deepspeech
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Bingo123
      - MONGO_INITDB_DATABASE=deepspeech
    networks:
      - deepspeech

networks:
  deepspeech:
    driver: bridge
