# Service definition for STT app
apiVersion: v1
kind: Service
metadata:
  name: stt-service
spec:
  selector:
    app: stt
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer

---

# Service definition for TTS app
apiVersion: v1
kind: Service
metadata:
  name: tts-service
spec:
  selector:
    app: tts
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer