openapi: 3.0.0
info:
  title: DEEPSPEECH_RW
  description: >-
    Welcome to the Kinyarwanda DeepSpeech API repository! This comprehensive guide provides an in depth exploration of this powerful end-to-end solution for speech processing in Kinyarwanda. With our DeepSpeech API, you can effortlessly convert spoken Kinyarwanda into text and transform text into natural-sounding Kinyarwanda speech.
    
  version: 1.0.0
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /stt/transcribe:
    post:
      tags:
        - General
      summary: Speech To Text
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                audio_bytes:
                  type: string
                  format: binary
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: number
                example: nginx/1.25.3
            Date:
              schema:
                type: string
                example: Wed, 08 Nov 2023 16:12:10 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '67'
            Connection:
              schema:
                type: string
                example: keep-alive
          content:
            application/json:
              schema:
                type: object
              example:
                sentences: mwaramutse wili ni igerageza rya ssatom ihimba ijwe
  /tts/generate:
    post:
      tags:
        - General
      summary: Text to Speech
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                text: Mwaramutseho, iri ni igerageza rya sisetumo ihimba ijwi
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: number
                example: nginx/1.25.3
            Date:
              schema:
                type: string
                example: Wed, 08 Nov 2023 16:12:10 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '67'
            Connection:
              schema:
                type: string
                example: keep-alive
          content:
            application/json:
              schema:
                type: object
              example:
                sentences: mwaramutse wili ni igerageza rya ssatom ihimba ijwe
